# -*-Fundamental-*-
#
# PROJECT C Library, X68000 PROGRAMMING INTERFACE DEFINITION
# --------------------------------------------------------------------
# This file is written by the Project C Library Group,  and completely
# in public domain. You can freely use, copy, modify, and redistribute
# the whole contents, without this notice.
# --------------------------------------------------------------------
# $Id: Makefile,v 1.3 1994/11/26 15:04:49 mura Exp $
#

   EXTRA_DEFINES =
 EXTRA_LIBRARIES =
      LIB_TARGET = ../../lib/libiocs.a
         OBJECTS = b_bitsns.o b_clr_al.o b_clr_ed.o b_clr_st.o \
		   b_color.o b_consol.o b_curoff.o b_curon.o \
		   b_del.o b_down.o b_down_s.o b_era_al.o \
		   b_era_ed.o b_era_st.o b_ins.o b_keyinp.o \
		   b_keysns.o b_left.o b_locate.o b_print.o \
		   b_putc.o b_putmes.o b_right.o b_sftsns.o \
		   b_up.o clipput.o contrast.o crtmod.o \
		   defchr.o fntget.o hsvtorgb.o \
		   ledmod.o scroll.o skeyset.o tcolor.o \
		   textget.o textput.o tgusemd.o tpalet.o \
		   tpalet2.o trap15.o tvctrl.o up_s.o \
		   b_assign.o b_badfmt.o b_drvchk.o b_drvsns.o \
		   b_dskini.o b_eject.o b_format.o b_read.o \
		   b_readdi.o b_readdl.o b_readid.o b_recali.o \
		   b_seek.o b_verify.o b_write.o b_writed.o \
		   init_prn.o inp232c.o isns232c.o joyget.o \
		   lof232c.o osns232c.o out232c.o outlpt.o \
		   outprn.o set232c.o snsprn.o \
		   adpcmain.o adpcmaot.o adpcminp.o adpcmlin.o \
		   adpcmlot.o adpcmmod.o adpcmout.o adpcmsns.o \
		   alarmget.o alarmmod.o alarmset.o bindatebcd.o \
		   bindateget.o bindateset.o crtcras.o dateasc.o \
		   datebin.o datecnv.o dayasc.o hsyncst.o \
		   opmintst.o opmset.o opmsns.o prnintst.o \
		   timeasc.o timebcd.o timebin.o timecnv.o \
		   timeget.o timerdst.o timeset.o vdispt.o \
		   skey_mod.o \
		   akconv.o b_bpeek.o b_bpoke.o b_intvcs.o \
		   b_lpeek.o b_lpoke.o b_memset.o b_memstr.o \
		   b_super.o b_wpeek.o b_wpoke.o bootinf.o \
		   densns.o dmamode.o dmamov_a.o dmamov_l.o \
		   dmamove.o g_clr_on.o gpalet.o jissft.o \
		   ms_curgt.o ms_curof.o ms_curon.o ms_curst.o \
		   ms_getdt.o ms_init.o ms_limit.o ms_offtm.o \
		   ms_ontm.o ms_patst.o ms_sel.o ms_sel2.o \
		   ms_stat.o ontime.o romver.o sftjis.o \
		   abortjob.o abortrst.o apage.o bgctrlgt.o \
		   bgctrlst.o bgscrlgt.o bgscrlst.o bgtextcl.o \
		   bgtextgt.o bgtextst.o box.o circle.o \
		   dakjob.o fill.o getgrm.o hanjob.o \
		   home.o iplerr.o line.o os_curof.o \
		   os_curon.o paint.o point.o pset.o \
		   putgrm.o rmacnv.o sp_cgclr.o sp_defcg.o \
		   sp_gtpcg.o sp_init.o sp_off.o sp_on.o \
		   sp_reggt.o sp_regst.o spalet.o symbol.o \
		   txbox.o txfill.o txrascpy.o txrev.o \
		   txxline.o txyline.o vpage.o window.o \
		   wipe.o

include ../DefaultBases
include ../DefaultRules
