# -*-Fundamental-*-
#
# PROJECT C Library, X68000 PROGRAMMING INTERFACE DEFINITION
# --------------------------------------------------------------------
# This file is written by the Project C Library Group,  and completely
# in public domain. You can freely use, copy, modify, and redistribute
# the whole contents, without this notice.
# --------------------------------------------------------------------
# $Id: Makefile,v 1.4 1994/11/26 15:02:15 mura Exp $
#

   EXTRA_DEFINES =
 EXTRA_LIBRARIES =
      LIB_TARGET = ../../lib/libdos.a
         OBJECTS = allclose.o bindno.o breakck.o memcpy.o \
		   c_cls_al.o c_cls_ed.o c_cls_st.o c_color.o \
		   c_curoff.o c_curon.o c_del.o c_down.o \
		   c_down_s.o c_era_al.o c_era_ed.o c_era_st.o \
		   c_fnkmod.o c_ins.o c_left.o c_locate.o \
		   c_print.o c_putc.o c_right.o c_up.o \
		   c_up_s.o c_width.o c_window.o change_pr.o \
		   chdir.o chgdrv.o chmod.o cinsns.o \
		   close.o cominp.o common_ck.o common_del.o \
		   common_fre.o common_lk.o common_rd.o common_wt.o \
		   comout.o consns.o coutsns.o create.o curdir.o \
		   curdrv.o delete.o diskred.o diskred2.o \
		   diskwrt.o diskwrt2.o drvctrl.o drvxchg.o \
		   dskfre.o dup.o dup0.o dup2.o \
		   exec2.o execonly.o exit.o exit2.o \
		   fatchk.o fatchk2.o getfcb.o retshell.o \
		   ctlabort.o errabort.o fflush.o fgetc.o \
		   fgets.o filedate.o files.o fnckeygt.o \
		   fnckeyst.o fputc.o fputs.o get_pr.o \
		   getassign.o getc.o getchar.o getdate.o \
		   getdpb.o getenv.o getpdb.o gets.o \
		   getss.o gettim2.o gettime.o hendspic.o \
		   hendspio.o hendspip.o hendspir.o hendspmc.o \
		   hendspmo.o hendspmp.o hendspmr.o hendspsc.o \
		   hendspso.o hendspsp.o hendspsr.o indosflg.o \
		   inkey.o inpout.o intvcg.o intvcs.o \
		   ioctrldvctl.o ioctrldvgt.o ioctrlfdctl.o ioctrlfdgt.o \
		   ioctrlgt.o ioctrlis.o ioctrlos.o ioctrlrd.o \
		   ioctrlrh.o ioctrlrtset.o ioctrlst.o ioctrlwd.o \
		   ioctrlwh.o k_insmod.o k_keybit.o k_keyinp.o \
		   k_keysns.o k_sftsns.o keeppr.o keysns.o \
		   kflushgc.o kflushgp.o kflushgs.o kflushin.o \
		   kflushio.o kill_pr.o load.o loadexec.o \
		   loadonly.o lock.o makeassign.o maketmp.o \
		   malloc.o malloc2.o mfree.o mkdir.o \
		   move.o nameck.o namests.o newfile.o \
		   nfiles.o open.o open_pr.o pathchk.o \
		   print.o prnout.o prnsns.o pspset.o \
		   putchar.o rassign.o read.o rename.o \
		   rmdir.o s_malloc.o s_mfree.o s_process.o \
		   seek.o send_pr.o setblock.o setdate.o \
		   setenv.o setpdb.o settim2.o settime.o \
		   sleep_pr.o super.o super_jsr.o suspend_pr.o \
		   time_pr.o unlock.o verify.o verifyg.o \
		   vernum.o wait.o write.o

include ../DefaultBases
include ../DefaultRules
