# -*-Fundamental-*-
#
# PROJECT C Library, X68000 PROGRAMMING INTERFACE DEFINITION
# --------------------------------------------------------------------
# This file is written by the Project C Library Group,  and completely
# in public domain. You can freely use, copy, modify, and redistribute
# the whole contents, without this notice.
# --------------------------------------------------------------------
# $Id: Makefile,v 1.2 1994/11/26 14:54:08 mura Exp $
#

   EXTRA_DEFINES =
 EXTRA_LIBRARIES =
      LIB_TARGET = ../../lib/libmb.a
         OBJECTS = ismbbalnum.o ismbbalpha.o ismbbgraph.o ismbbkalnum.o \
		   ismbbkana.o ismbbkpunct.o ismbblead.o ismbbprint.o ismbbpunct.o \
		   ismbbtrail.o ismbcalpha.o ismbcdigit.o ismbchira.o ismbckata.o \
		   ismbcl0.o ismbcl1.o ismbcl2.o ismbclegal.o ismbclower.o \
		   ismbcprint.o ismbcspace.o ismbcsymbol.o ismbcupper.o mbctohira.o \
		   mbctokata.o mbctolower.o mbctoupper.o

include ../DefaultBases
include ../DefaultRules
