# -*-Fundamental-*-
#
# PROJECT C Library, X68000 PROGRAMMING INTERFACE DEFINITION
# --------------------------------------------------------------------
# This file is written by the Project C Library Group,  and completely
# in public domain. You can freely use, copy, modify, and redistribute
# the whole contents, without this notice.
# --------------------------------------------------------------------
# $Id: Makefile,v 1.6 1994/11/26 14:58:06 mura Exp $
#

   EXTRA_DEFINES =
 EXTRA_LIBRARIES =
      LIB_TARGET = ../../lib/libc.a
         OBJECTS = _dtos18.o _fullentry.o _fullpath.o _getdriveno.o _ma_add.o \
		   _ma_new.o _ma_remove.o _ma_recycle.o _ma_search.o _makepath.o \
		   _path.o _round.o _splitpath.o _ultoa.o _ulltoa.o abort.o abs.o \
		   atexit.o atof.o atoi.o atow.o brk.o bsearch.o calloc.o chkml.o \
		   clearenv.o div.o drand.o econvert.o exit.o fconvert.o fcvt.o \
		   free.o gcvt.o getenv.o getopt.o itoa.o ldiv.o ltoa.o malloc.o \
		   mallocmap.o mblen.o mbstowcs.o mbtowc.o mkstemp.o mktemp.o \
		   onexit.o putenv.o qsort.o rand.o rand48.o random.o rbrk.o \
		   realloc.o sbrk.o setenv.o sizmem.o srand.o strtod.o strtol.o \
		   strtoul.o system.o ultoa.o unsetenv.o wabs.o wcstombs.o wctomb.o

include ../DefaultBases
include ../DefaultRules
