# -*-Fundamental-*-
#
# PROJECT C Library, X68000 PROGRAMMING INTERFACE DEFINITION
# --------------------------------------------------------------------
# This file is written by the Project C Library Group,  and completely
# in public domain. You can freely use, copy, modify, and redistribute
# the whole contents, without this notice.
# --------------------------------------------------------------------
# $Id: Makefile,v 1.3 1994/11/26 14:57:01 mura Exp $
#

   EXTRA_DEFINES = -D__NO_STDIO_INLINE__
 EXTRA_LIBRARIES =
      LIB_TARGET = ../../lib/libc.a
         OBJECTS = _doprnt.o _doscan.o _empty.o _sclose.o _sinit.o _sopen.o \
		   _sread.o _swrite.o clearerr.o eprintf.o fclose.o fcloseall.o \
		   fdopen.o feof.o ferror.o fflush.o fgetc.o fgetpos.o fgets.o \
		   fileno.o flushall.o fmode.o fopen.o fprintf.o fputc.o fputs.o \
		   fread.o freopen.o fscanf.o fseek.o fsetpos.o ftell.o fwrite.o \
		   getchar.o gets.o getw.o pclose.o perror.o popen.o printf.o \
		   psignal.o putchar.o puts.o putw.o remove.o rewind.o scanf.o \
		   setbuf.o setvbuf.o sprintf.o sscanf.o tempnam.o tmpfile.o \
		   tmpnam.o ungetc.o vfprintf.o vfscanf.o vprintf.o vscanf.o \
		   vsscanf.o vsprintf.o rename.o

include ../DefaultBases
include ../DefaultRules
