# -*-Fundamental-*-
#
# PROJECT C Library, X68000 PROGRAMMING INTERFACE DEFINITION
# --------------------------------------------------------------------
# This file is written by the Project C Library Group,  and completely
# in public domain. You can freely use, copy, modify, and redistribute
# the whole contents, without this notice.
# --------------------------------------------------------------------
# $Id: Makefile,v 1.2 1994/11/26 15:13:59 mura Exp $
#

   EXTRA_DEFINES =
 EXTRA_LIBRARIES =
      LIB_TARGET = ../../lib/libw.a
         OBJECTS = wcscat.o wcschr.o wcscmp.o wcscpy.o wcscspn.o wcsdup.o \
		   wcslen.o wcsncat.o wcsncmp.o wcsncpy.o wcspbrk.o wcsrchr.o \
		   wcsspn.o wcstok.o

include ../DefaultBases
include ../DefaultRules
