# -*-Fundamental-*-
#
# PROJECT C Library, X68000 PROGRAMMING INTERFACE DEFINITION
# --------------------------------------------------------------------
# This file is written by the Project C Library Group,  and completely
# in public domain. You can freely use, copy, modify, and redistribute
# the whole contents, without this notice.
# --------------------------------------------------------------------
# $Id: Makefile,v 1.6 1994/11/26 14:56:23 mura Exp $
#

   EXTRA_DEFINES =
 EXTRA_LIBRARIES =
      LIB_TARGET = ../../lib/libc.a
         OBJECTS = _cplus.o _ctors.o _blkprof.o _dehupair.o _dumsig.o _enargv.o \
		   _exit.o _enhupair.o _fncprof.o _heapdef.o _heapsiz.o _main.o \
		   _pinfo.o _start.o _stack.o _stackdef.o _stacksiz.o _superman.o \
		   _vars.o _vector.o

include ../DefaultBases
include ../DefaultRules
