# -*-Fundamental-*-
#
# PROJECT C Library, X68000 PROGRAMMING INTERFACE DEFINITION
# --------------------------------------------------------------------
# This file is written by the Project C Library Group,  and completely
# in public domain. You can freely use, copy, modify, and redistribute
# the whole contents, without this notice.
# --------------------------------------------------------------------
# $Id: Makefile,v 1.2 1994/11/26 15:13:40 mura Exp $
#

   EXTRA_DEFINES =
 EXTRA_LIBRARIES =
      LIB_TARGET = ../../lib/libw.a
         OBJECTS = iswalnum.o iswalpha.o iswascii.o iswcntrl.o iswdigit.o \
		   iswgraph.o iswlower.o iswprint.o iswpunct.o iswspace.o \
		   iswupper.o iswxdigit.o towlower.o towupper.o

include ../DefaultBases
include ../DefaultRules
