# -*-Fundamental-*-
#
# PROJECT C Library, X68000 PROGRAMMING INTERFACE DEFINITION
# --------------------------------------------------------------------
# This file is written by the Project C Library Group,  and completely
# in public domain. You can freely use, copy, modify, and redistribute
# the whole contents, without this notice.
# --------------------------------------------------------------------
# $Id: Makefile,v 1.2 1994/11/26 15:08:00 mura Exp $
#

   EXTRA_DEFINES =
 EXTRA_LIBRARIES =
      LIB_TARGET = ../../lib/libc.a
         OBJECTS = _isleap.o _getleaps.o _getmday.o _getyday.o asctime.o \
		   clock.o ctime.o difftime.o gmtime.o localtime.o mktime.o \
		   strftime.o time.o dumtz.o

include ../DefaultBases
include ../DefaultRules
