# -*-Fundamental-*-
#
# PROJECT C Library, X68000 PROGRAMMING INTERFACE DEFINITION
# --------------------------------------------------------------------
# This file is written by the Project C Library Group,  and completely
# in public domain. You can freely use, copy, modify, and redistribute
# the whole contents, without this notice.
# --------------------------------------------------------------------
# $Id: Makefile,v 1.3 1994/11/26 15:05:47 mura Exp $
#

   EXTRA_DEFINES =
 EXTRA_LIBRARIES =
      LIB_TARGET =
      LIB_TARGET = ../../lib/libscsi.a
         OBJECTS = cmdout.o datain.o datain_p.o dataout.o dataout_p.o \
		   format.o inquiry.o modeselect.o modesense.o msgin.o \
		   msgout.o pamedium.o phase.o read.o readcap.o readext.o \
		   reassign.o request.o reset.o rezerounit.o seek.o \
		   select.o startstop.o stsin.o testunit.o write.o writeext.o

include ../DefaultBases
include ../DefaultRules
