# -*-Fundamental-*-
#
# PROJECT C Library, X68000 PROGRAMMING INTERFACE DEFINITION
# --------------------------------------------------------------------
# This file is written by the Project C Library Group,  and completely
# in public domain. You can freely use, copy, modify, and redistribute
# the whole contents, without this notice.
# --------------------------------------------------------------------
# $Id: Makefile,v 1.5 1994/11/27 13:02:47 mura Exp $
#

   EXTRA_DEFINES =
 EXTRA_LIBRARIES =
      LIB_TARGET = ../../lib/libmb.a
         OBJECTS = _mblen.o _mbset.o mbbtombc.o mbbtype.o mbctombb.o mbsbtype.o \
		   mbscat.o mbschr.o mbscmp.o mbscpy.o mbscspn.o mbsdup.o mbsicmp.o \
		   mbsinc.o mbslen.o mbslwr.o mbsnbcnt.o mbsncat.o mbsnccnt.o \
		   mbsncmp.o mbsncpy.o mbsnextc.o mbsnicmp.o mbsninc.o mbspbrk.o \
		   mbsrchr.o mbsrev.o mbsset.o mbsspn.o mbsspnp.o mbstok.o mbsupr.o

include ../DefaultBases
include ../DefaultRules
