# -*-Fundamental-*-
#
# PROJECT C Library, X68000 PROGRAMMING INTERFACE DEFINITION
# --------------------------------------------------------------------
# This file is written by the Project C Library Group,  and completely
# in public domain. You can freely use, copy, modify, and redistribute
# the whole contents, without this notice.
# --------------------------------------------------------------------
# $Id: Makefile,v 1.2 1994/11/26 14:51:32 mura Exp $
#

   EXTRA_DEFINES =
 EXTRA_LIBRARIES =
      LIB_TARGET = ../../lib/libc.a
         OBJECTS = _ctype.o _lower.o _mbctype.o _upper.o isalnum.o isalpha.o \
		   isascii.o isblank.o iscntrl.o iscsym.o iscsymf.o isdigit.o \
		   isgraph.o isiso.o islower.o isodigit.o isprint.o ispunct.o \
		   isspace.o isupper.o isxdigit.o toascii.o toiso.o tolower.o \
		   toupper.o

include ../DefaultBases
include ../DefaultRules
