# -*-Fundamental-*-
#
# PROJECT C Library, X68000 PROGRAMMING INTERFACE DEFINITION
# --------------------------------------------------------------------
# This file is written by the Project C Library Group,  and completely
# in public domain. You can freely use, copy, modify, and redistribute
# the whole contents, without this notice.
# --------------------------------------------------------------------
# $Id: Makefile,v 1.5 1994/11/26 14:59:46 mura Exp $
#

   EXTRA_DEFINES =
 EXTRA_LIBRARIES =
      LIB_TARGET = ../../lib/libc.a
         OBJECTS = bcmp.o bcopy.o bzero.o ffs.o index.o memccpy.o memchr.o \
		   memcmp.o memcpy.o memicmp.o memmove.o memset.o repmem.o \
		   rindex.o stcgfe.o stcgfn.o stpcpy.o strbpl.o strcat.o \
		   strchr.o strcmp.o strcoll.o strcpy.o strcspn.o strdup.o \
		   strerror.o stricmp.o strins.o strlen.o strlwr.o strmfe.o \
		   strmfn.o strmfp.o strncat.o strncmp.o strncpy.o strnicmp.o \
		   strnset.o strpbrk.o strrchr.o strrev.o strset.o strsfn.o \
		   strspn.o strsrt.o strstr.o strtok.o strtok2.o strupr.o \
		   strxfrm.o swab.o swmem.o

include ../DefaultBases
include ../DefaultRules
