# -*-Fundamental-*-
#
# PROJECT C Library, X68000 PROGRAMMING INTERFACE DEFINITION
# --------------------------------------------------------------------
# This file is written by the Project C Library Group,  and completely
# in public domain. You can freely use, copy, modify, and redistribute
# the whole contents, without this notice.
# --------------------------------------------------------------------
# $Id: Makefile,v 1.4 1994/11/26 15:09:13 mura Exp $
#

   EXTRA_DEFINES =
 EXTRA_LIBRARIES =
      LIB_TARGET = ../../lib/libc.a
         OBJECTS = _appfd.o _close.o _exec.o _finit.o _md2d.o _md2u.o _open.o \
		   _pconf.o _return.o _seekeof.o _sleep.o _spawn.o _usedfd.o \
		   _writable.o access.o alarm.o chdir.o chdrive.o chown.o \
		   chsize.o close.o closeall.o commit.o ctermid.o cuserid.o \
		   dup.o dup2.o execl.o execle.o execlp.o execv.o execve.o \
		   execvp.o fchown.o filelength.o fpathconf.o ftruncate.o \
		   getcwd.o getdcwd.o getdrive.o getegid.o geteuid.o getgid.o \
		   getlogin.o getpagesize.o getpgrp.o getpid.o getppid.o \
		   getuid.o getwd.o isatty.o lseek.o nice.o pathconf.o pause.o \
		   read.o readlink.o rmdir.o setgid.o setgroups.o setmode.o \
		   setpgid.o setsid.o setuid.o sleep.o spawnl.o spawnle.o \
		   spawnlp.o spawnv.o spawnve.o spawnvp.o symlink.o sysconf.o \
		   tcgetpgrp.o tcsetpgrp.o tell.o truncate.o ttyname.o \
		   unlink.o usleep.o write.o

include ../DefaultBases
include ../DefaultRules
