# -*-Fundamental-*-
#
# PROJECT C Library, X68000 PROGRAMMING INTERFACE DEFINITION
# --------------------------------------------------------------------
# This file is written by the Project C Library Group,  and completely
# in public domain. You can freely use, copy, modify, and redistribute
# the whole contents, without this notice.
# --------------------------------------------------------------------
# $Id: Makefile,v 1.2 1994/11/26 15:06:04 mura Exp $
#

   EXTRA_DEFINES =
 EXTRA_LIBRARIES =
      LIB_TARGET = ../../lib/libc.a
         OBJECTS = _stat.o chmod.o fchmod.o fstat.o lstat.o mkdir.o \
		   stat.o umask.o _getinode.o

include ../DefaultBases
include ../DefaultRules
