# -*-Fundamental-*-
#
# PROJECT C Library, X68000 PROGRAMMING INTERFACE DEFINITION
# --------------------------------------------------------------------
# This file is written by the Project C Library Group,  and completely
# in public domain. You can freely use, copy, modify, and redistribute
# the whole contents, without this notice.
# --------------------------------------------------------------------
# $Id: Makefile,v 1.6 1994/11/26 14:55:39 mura Exp $
#

   EXTRA_DEFINES =
 EXTRA_LIBRARIES =
      LIB_TARGET = ../../lib/libsignal.a
         OBJECTS = _harderr.o _intabt.o _intctl.o _interr.o _intrtc.o _raise.o \
		   _sigclrcnt.o _sigdfl.o _sigdisp.o _sigend.o _siginit.o _siglist.o \
		   _signal.o _sigparse.o _sigrtcsave.o _sigsetcnt.o abort.o kill.o \
		   longjmp.o raise.o setjmp.o sigaction.o sigblock.o sigaddset.o \
		   sigdelset.o sigemptyset.o sigfillset.o sigismember.o siglongjmp.o \
		   signal.o sigpending.o sigprocmask.o sigsetjmp.o sigsetmask.o \
		   sigsuspend.o strsignal.o

include ../DefaultBases
include ../DefaultRules

