/*
 * PROJECT C Library, X68000 PROGRAMMING INTERFACE DEFINITION
 * --------------------------------------------------------------------
 * This file is written by the Project C Library Group,  and completely
 * in public domain. You can freely use, copy, modify, and redistribute
 * the whole contents, without this notice.
 * --------------------------------------------------------------------
 * $Id: iocs_p.h,v 1.5 1993/10/06 16:46:12 mura Exp $
 */

#ifndef __sys_iocs_p_h__
#define __sys_iocs_p_h__

_EXTERN (int_ __const _iocs_akconv (int_, int_));
_EXTERN (int_ __const _iocs_bootinf (void_));
_EXTERN (int_ __const _iocs_hsvtorgb (int_, int_, int_));
_EXTERN (int_ __const _iocs_jissft (int_));
_EXTERN (int_ __const _iocs_romver (void_));
_EXTERN (int_ __const _iocs_sftjis (int_));
_EXTERN (int_ _iocs_adpcmsns (void_));
_EXTERN (int_ _iocs_alarmget (int_ *, int_ *, int_ *));
_EXTERN (int_ _iocs_alarmmod (int_));
_EXTERN (int_ _iocs_alarmset (int_, int_, int_));
_EXTERN (int_ _iocs_apage (int_));
_EXTERN (int_ _iocs_b_assign (int_, int_, int_, const void *));
_EXTERN (int_ _iocs_b_badfmt (int_, int_, int_));
_EXTERN (int_ _iocs_b_bpeek (const void *));
_EXTERN (int_ _iocs_b_color (int_));
_EXTERN (int_ _iocs_b_consol (int_, int_, int_, int_));
_EXTERN (int_ _iocs_b_drvchk (int_, int_));
_EXTERN (int_ _iocs_b_drvsns (int_));
_EXTERN (int_ _iocs_b_dskini (int_, const void *, int_));
_EXTERN (int_ _iocs_b_eject (int_));
_EXTERN (int_ _iocs_b_format (int_, int_, int_, const void *));
_EXTERN (int_ _iocs_b_intvcs (int_, int_));
_EXTERN (int_ _iocs_b_keyinp (void_));
_EXTERN (int_ _iocs_b_keysns (void_));
_EXTERN (int_ _iocs_b_locate (int_, int_));
_EXTERN (int_ _iocs_b_lpeek (const void *));
_EXTERN (int_ _iocs_b_print (const char *));
_EXTERN (int_ _iocs_b_putc (int_));
_EXTERN (int_ _iocs_b_putmes (int_, int_, int_, int_, const char *));
_EXTERN (int_ _iocs_b_read (int_, int_, int_, void *));
_EXTERN (int_ _iocs_b_readdi (int_, int_, int_, void *));
_EXTERN (int_ _iocs_b_readdl (int_, int_, int_, void *));
_EXTERN (int_ _iocs_b_readid (int_, int_, void *));
_EXTERN (int_ _iocs_b_recali (int_));
_EXTERN (int_ _iocs_b_seek (int_, int_));
_EXTERN (int_ _iocs_b_sftsns (void_));
_EXTERN (int_ _iocs_b_super (int_));
_EXTERN (int_ _iocs_b_verify (int_, int_, int_, const void *));
_EXTERN (int_ _iocs_b_wpeek (const void *));
_EXTERN (int_ _iocs_b_write (int_, int_, int_, const void *));
_EXTERN (int_ _iocs_b_writed (int_, int_, int_, const void *));
_EXTERN (int_ _iocs_bgctrlgt (int_));
_EXTERN (int_ _iocs_bgctrlst (int_, int_, int_));
_EXTERN (int_ _iocs_bgscrlgt (int_, int_ *, int_ *));
_EXTERN (int_ _iocs_bgscrlst (int_, int_, int_));
_EXTERN (int_ _iocs_bgtextcl (int_, int_));
_EXTERN (int_ _iocs_bgtextgt (int_, int_, int_));
_EXTERN (int_ _iocs_bgtextst (int_, int_, int_, int_));
_EXTERN (int_ _iocs_bindatebcd (int_));
_EXTERN (int_ _iocs_bindateget (void_));
_EXTERN (int_ _iocs_bitsns (int_));
_EXTERN (int_ _iocs_box (const struct _boxptr *));
_EXTERN (int_ _iocs_circle (const struct _circleptr *));
_EXTERN (int_ _iocs_contrast (int_));
_EXTERN (int_ _iocs_crtcras (const void *, int_));
_EXTERN (int_ _iocs_crtmod (int_));
_EXTERN (int_ _iocs_dakjob (char *));
_EXTERN (int_ _iocs_dateasc (int_, char *));
_EXTERN (int_ _iocs_datebin (int_));
_EXTERN (int_ _iocs_datecnv (const char *));
_EXTERN (int_ _iocs_defchr (int_, int_, const void *));
_EXTERN (int_ _iocs_dmamode (void_));
_EXTERN (int_ _iocs_fill (const struct _fillptr *));
_EXTERN (int_ _iocs_fntget (int_, int_, struct _fntbuf *));
_EXTERN (int_ _iocs_getgrm (struct _getptr *));
_EXTERN (int_ _iocs_gpalet (int_, int_));
_EXTERN (int_ _iocs_hanjob (char *));
_EXTERN (int_ _iocs_home (int_, int_, int_));
_EXTERN (int_ _iocs_hsyncst (const void *));
_EXTERN (int_ _iocs_init_prn (int_, int_));
_EXTERN (int_ _iocs_inp232c (void_));
_EXTERN (int_ _iocs_isns232c (void_));
_EXTERN (int_ _iocs_joyget (int_));
_EXTERN (int_ _iocs_line (const struct _lineptr *));
_EXTERN (int_ _iocs_lof232c (void_));
_EXTERN (int_ _iocs_ms_curgt (void_));
_EXTERN (int_ _iocs_ms_curst (int_, int_));
_EXTERN (int_ _iocs_ms_getdt (void_));
_EXTERN (int_ _iocs_ms_limit (int_, int_, int_, int_));
_EXTERN (int_ _iocs_ms_offtm (int_, int_));
_EXTERN (int_ _iocs_ms_ontm (int_, int_));
_EXTERN (int_ _iocs_ms_stat (void_));
_EXTERN (int_ _iocs_ontime (void_));
_EXTERN (int_ _iocs_opmintst (const void *));
_EXTERN (int_ _iocs_opmsns (void_));
_EXTERN (int_ _iocs_osns232c (void_));
_EXTERN (int_ _iocs_paint (struct _paintptr *));
_EXTERN (int_ _iocs_point (const struct _pointptr *));
_EXTERN (int_ _iocs_prnintst (const void *));
_EXTERN (int_ _iocs_pset (const struct _psetptr *));
_EXTERN (int_ _iocs_putgrm (const struct _putptr *));
_EXTERN (int_ _iocs_rmacnv (int_, char *, char *));
_EXTERN (int_ _iocs_set232c (int_));
_EXTERN (int_ _iocs_skey_mod (int_, int_, int_));
_EXTERN (int_ _iocs_snsprn (void_));
_EXTERN (int_ _iocs_sp_cgclr (int_));
_EXTERN (int_ _iocs_sp_defcg (int_, int_, const void *));
_EXTERN (int_ _iocs_sp_gtpcg (int_, int_, void *));
_EXTERN (int_ _iocs_sp_init (void_));
_EXTERN (int_ _iocs_sp_on (void_));
_EXTERN (int_ _iocs_sp_reggt (int_, int_ *, int_ *, int_ *, int_ *));
_EXTERN (int_ _iocs_sp_regst (int_, int_, int_, int_, int_, int_));
_EXTERN (int_ _iocs_spalet (int_, int_, int_));
_EXTERN (int_ _iocs_symbol (const struct _symbolptr *));
_EXTERN (int_ _iocs_tgusemd (int_, int_));
_EXTERN (int_ _iocs_timeasc (int_, char *));
_EXTERN (int_ _iocs_timebcd (int_));
_EXTERN (int_ _iocs_timebin (int_));
_EXTERN (int_ _iocs_timecnv (const char *));
_EXTERN (int_ _iocs_timeget (void_));
_EXTERN (int_ _iocs_timerdst (const void *, int_, int_));
_EXTERN (int_ _iocs_tpalet (int_, int_));
_EXTERN (int_ _iocs_tpalet2 (int_, int_));
_EXTERN (int_ _iocs_trap15 (const struct _regs *, struct _regs *));
_EXTERN (int_ _iocs_vdispst (const void *, int_, int_));
_EXTERN (int_ _iocs_vpage (int_));
_EXTERN (int_ _iocs_window (int_, int_, int_, int_));
_EXTERN (int_ _iocs_wipe (void_));
_EXTERN (void __volatile _iocs_abortjob (void_));
_EXTERN (void __volatile _iocs_iplerr (void_));
_EXTERN (void _iocs_abortrst (void_));
_EXTERN (void _iocs_adpcmain (const struct _chain *, int_, int_));
_EXTERN (void _iocs_adpcmaot (const struct _chain *, int_, int_));
_EXTERN (void _iocs_adpcminp (void *, int_, int_));
_EXTERN (void _iocs_adpcmlin (const struct _chain2 *, int_));
_EXTERN (void _iocs_adpcmlot (const struct _chain2 *, int_));
_EXTERN (void _iocs_adpcmmod (int_));
_EXTERN (void _iocs_adpcmout (const void *, int_, int_));
_EXTERN (void _iocs_b_bpoke (void *, int_));
_EXTERN (void _iocs_b_clr_al (void_));
_EXTERN (void _iocs_b_clr_ed (void_));
_EXTERN (void _iocs_b_clr_st (void_));
_EXTERN (void _iocs_b_curoff (void_));
_EXTERN (void _iocs_b_curon (void_));
_EXTERN (void _iocs_b_del (int_));
_EXTERN (void _iocs_b_down (int_));
_EXTERN (void _iocs_b_down_s (void_));
_EXTERN (void _iocs_b_era_al (void_));
_EXTERN (void _iocs_b_era_ed (void_));
_EXTERN (void _iocs_b_era_st (void_));
_EXTERN (void _iocs_b_ins (int_));
_EXTERN (void _iocs_b_left (int_));
_EXTERN (void _iocs_b_lpoke (void *, int_));
_EXTERN (void _iocs_b_memset (void *, const void *, int_));
_EXTERN (void _iocs_b_memstr (const void *, void *, int_));
_EXTERN (void _iocs_b_right (int_));
_EXTERN (void _iocs_b_up (int_));
_EXTERN (void _iocs_b_up_s (void_));
_EXTERN (void _iocs_b_wpoke (void *, int_));
_EXTERN (void _iocs_bindateset (int_));
_EXTERN (void _iocs_clipput (int_, int_, const struct _fntbuf *, const struct _clipxy *));
_EXTERN (void _iocs_dayasc (int_, char *));
_EXTERN (void _iocs_densns (void_));
_EXTERN (void _iocs_dmamov_a (const struct _chain *, void *, int_, int_));
_EXTERN (void _iocs_dmamov_l (const struct _chain2 *, void *, int_));
_EXTERN (void _iocs_dmamove (void *, void *, int_, int_));
_EXTERN (void _iocs_g_clr_on (void_));
_EXTERN (void _iocs_ledmod (int_, int_));
_EXTERN (void _iocs_ms_curof (void_));
_EXTERN (void _iocs_ms_curon (void_));
_EXTERN (void _iocs_ms_init (void_));
_EXTERN (void _iocs_ms_patst (int_, const struct _patst *));
_EXTERN (void _iocs_ms_sel (int_));
_EXTERN (void _iocs_ms_sel2 (const short *));
_EXTERN (void _iocs_opmset (int_, int_));
_EXTERN (void _iocs_os_curof (void_));
_EXTERN (void _iocs_os_curon (void_));
_EXTERN (void _iocs_out232c (int_));
_EXTERN (void _iocs_outlpt (int_));
_EXTERN (void _iocs_outprn (int_));
_EXTERN (void _iocs_scroll (int_, int_, int_));
_EXTERN (void _iocs_skeyset (int_));
_EXTERN (void _iocs_sp_off (void_));
_EXTERN (void _iocs_tcolor (int_));
_EXTERN (void _iocs_textget (int_, int_, struct _fntbuf *));
_EXTERN (void _iocs_textput (int_, int_, const struct _fntbuf *));
_EXTERN (void _iocs_timeset (int_));
_EXTERN (void _iocs_tvctrl (int_));
_EXTERN (void _iocs_txbox (const struct _tboxptr *));
_EXTERN (void _iocs_txfill (const struct _txfillptr *));
_EXTERN (void _iocs_txrascpy (int_, int_, int_));
_EXTERN (void _iocs_txrev (const struct _trevptr *));
_EXTERN (void _iocs_txxline (const struct _xlineptr *));
_EXTERN (void _iocs_txyline (const struct _ylineptr *));

#endif
